### ISSUE TITLE
The money amount is weird

### ISSUE THREAD

**Issue by FireFire9487** [chocolf/MoneyFromMobs#22]
I have just set the settings like this:
```
ZOMBIE:
  Enabled: true
  Min: 10
  Max: 50
  DropChance: 100
  NumberOfDrops: 5-10
  OnlyOnKill: true
```
and it drops 0~9 money 
WEIRD
